### ISSUE TITLE
Can't see the Interegator tab

### ISSUE THREAD

**Issue by sbuldan** [pharmapsychotic/clip-interrogator-ext#16]
Hello I am getting this errror

Closing server running on port: 7860
Restarting UI...
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "C:\GitHub\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\GitHub\stable-diffusion-webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 9, in <module>
    import clip_interrogator
ModuleNotFoundError: No module named 'clip_interrogator'

**Comment by sbuldan** [comment]
I think apply and restart didn't worked. I closed the command prompt window and restarted both automatic1111 and then refreshed web ui, now I can see the interregator tab.
