### ISSUE TITLE
Extension not working since latest update

### ISSUE THREAD

**Issue by tarunabhdutta** [pharmapsychotic/clip-interrogator-ext#25]
Error verifying new BLIP Large pickled file. Can I download it manually to solve the issue?

HERE IS THE ERROR:

Loading CLIP Interrogator 0.6.0...
Loading caption model blip-large...
Error verifying pickled file from C:\Users\TD FILM STUDIO/.cache\huggingface\hub\models--Salesforce--blip-image-captioning-large\snapshots\44f04d56320e7d169fec18c4b19f7efb9ab83105\pytorch_model.bin:
Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Program Files\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "C:\SD\stable-diffusion-webui-master\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\SD\stable-diffusion-webui-master\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 128, in image_to_prompt
    load(clip_model_name, caption_model_name)
  File "C:\SD\stable-diffusion-webui-master\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 66, in load
    ci = Interrogator(config)
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 70, in __init__
    self.load_caption_model()
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 84, in load_caption_model
    caption_model = BlipForConditionalGeneration.from_pretrained(model_path, torch_dtype=self.dtype)
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\transformers\modeling_utils.py", line 2480, in from_pretrained
    loaded_state_dict_keys = list(state_dict.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by keenmouse** [comment]
Is it failing to validate pytorch_model.bin because your virus scanner is removing it as soon as it's downloaded? I think you might be having the same problem being discussed [here](https://github.com/invoke-ai/InvokeAI/issues/2989) and [here](https://itch.io/post/7509488). It may only be happening with Windows Defender.

**Comment by tripletto** [comment]
I have the same problem and after adding --disable-safe-unpickle to get over this error I got a new one, which seem to result of a front slash instead of a backslash.

OSError: [Errno 22] Invalid argument: 'C:\\Users\\**myUsername/.cache**\\huggingface\\hub\\models--Salesforce--blip-image-captioning-base\\snapshots\\9f3084c0600e544506a2d414647492a036fb1aa0\\pytorch_model.bin'

**Comment by tripletto** [comment]
Can confirm, deactivating the Windows Defender real time protection made it work.

**Comment by tarunabhdutta** [comment]
No, windows defender and firewall were already turned off. Moreover turning off all the firewall and all my antivirus did not help. I tried manually downloading the pytorch_model.bin for 'BLIP Large' and put it in the Clip Interrogator folder inside model folder of A1111. That didn't help either.
Loading CLIP Interrogator 0.6.0...
Loading caption model blip-large...
Error verifying pickled file from C:\Users\TD FILM STUDIO/.cache\huggingface\hub\models--Salesforce--blip-image-captioning-large\snapshots\44f04d56320e7d169fec18c4b19f7efb9ab83105\pytorch_model.bin:
Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Program Files\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "C:\SD\stable-diffusion-webui-master\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\SD\stable-diffusion-webui-master\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 128, in image_to_prompt
    load(clip_model_name, caption_model_name)
  File "C:\SD\stable-diffusion-webui-master\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 66, in load
    ci = Interrogator(config)
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 70, in __init__
    self.load_caption_model()
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 84, in load_caption_model
    caption_model = BlipForConditionalGeneration.from_pretrained(model_path, torch_dtype=self.dtype)
  File "C:\SD\stable-diffusion-webui-master\venv\lib\site-packages\transformers\modeling_utils.py", line 2480, in from_pretrained
    loaded_state_dict_keys = list(state_dict.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by tripletto** [comment]
> You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

^^
From your error message. I had this as well and can confirm, that the extension works with this command line argument and the Windows Defender real time protection deactivated – which is pretty messy.

**Comment by caj001** [comment]
This used to work fine but now I get the following error with starting Automatic1111:

```
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "F:\Automatic1111\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\Automatic1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Automatic1111\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 10, in <module>
    from clip_interrogator import Config, Interrogator, list_caption_models, list_clip_models
ImportError: cannot import name 'list_caption_models' from 'clip_interrogator' (F:\Automatic1111\venv\lib\site-packages\clip_interrogator\__init__.py)
```

**Comment by pharmapsychotic** [comment]
@caj001 can you look up further in the output to see if it is failing to install clip_interrogator? It requires version 0.6.0 of clip_interrogator is installed. You can also try installing it manually to see what might be going wrong

```
F:\Automatic1111\> venv\Scripts\activate.bat
(venv) F:\Automatic1111\> pip install clip-interrogator==0.6.0
```

**Comment by caj001** [comment]
Thanks for the quick response. 

There is no file called activate.bat in the `venv\Scripts` directory. Mostly lots of .exe files.

Maybe something else is wrong with my A1111 installation?
I get this error when the script tries to load clip-interrogator:

Thanks!

```
F:\Automatic1111\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
F:\Automatic1111\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: quests is an invalid version and will not be supported in a future release
  warnings.warn(
No module 'xformers'. Proceeding without it.
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "F:\Automatic1111\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\Automatic1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Automatic1111\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 10, in <module>
    from clip_interrogator import Config, Interrogator, list_caption_models, list_clip_models
ImportError: cannot import name 'list_caption_models' from 'clip_interrogator' (F:\Automatic1111\venv\lib\site-packages\clip_interrogator\__init__.py)
```

**Comment by caj001** [comment]
Thanks for the quick response.  

There is no file called activate.bat in the venv\Scripts directory. Mostly lots of .exe files.  

Maybe something else is wrong with my A1111 installation?   I get this error when the script tries to load clip-interrogator:  

Thanks!  

```
Error running install.py for extension extensions\clip-interrogator-ext.
Command: "F:\Automatic1111\venv\Scripts\python.exe" "extensions\clip-interrogator-ext\install.py"
Error code: 1
stdout: Installing requirements for CLIP Interrogator

stderr: Traceback (most recent call last):
  File "F:\Automatic1111\extensions\clip-interrogator-ext\install.py", line 14, in <module>
    launch.run_pip(f"install clip-interrogator=={CI_VERSION}", "requirements for CLIP Interrogator")
  File "F:\Automatic1111\launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "F:\Automatic1111\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for CLIP Interrogator.
Command: "F:\Automatic1111\venv\Scripts\python.exe" -m pip install clip-interrogator==0.6.0 --prefer-binary
Error code: 1
stdout: Collecting clip-interrogator==0.6.0
  Using cached clip_interrogator-0.6.0-py3-none-any.whl (787 kB)
Collecting transformers>=4.27.1
  Using cached transformers-4.27.2-py3-none-any.whl (6.8 MB)
Requirement already satisfied: accelerate in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (0.15.0)
Requirement already satisfied: requests in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (2.28.2)
Requirement already satisfied: open-clip-torch in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (2.7.0)
Requirement already satisfied: Pillow in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (9.4.0)
Requirement already satisfied: safetensors in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (0.2.7)
Requirement already satisfied: torch in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (1.13.1+cu117)
Requirement already satisfied: torchvision in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (0.14.1+cu117)
Requirement already satisfied: tqdm in f:\automatic1111\venv\lib\site-packages (from clip-interrogator==0.6.0) (4.64.1)
Requirement already satisfied: numpy>=1.17 in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (1.23.3)
Requirement already satisfied: filelock in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (0.12.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (0.13.2)
Requirement already satisfied: pyyaml>=5.1 in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (6.0)
Requirement already satisfied: regex!=2019.12.17 in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (2022.10.31)
Requirement already satisfied: packaging>=20.0 in f:\automatic1111\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (23.0)
Requirement already satisfied: colorama in f:\automatic1111\venv\lib\site-packages (from tqdm->clip-interrogator==0.6.0) (0.4.6)
Requirement already satisfied: psutil in f:\automatic1111\venv\lib\site-packages (from accelerate->clip-interrogator==0.6.0) (5.9.4)
Requirement already satisfied: typing-extensions in f:\automatic1111\venv\lib\site-packages (from torch->clip-interrogator==0.6.0) (4.4.0)
Requirement already satisfied: ftfy in f:\automatic1111\venv\lib\site-packages (from open-clip-torch->clip-interrogator==0.6.0) (6.1.1)
Collecting protobuf==3.20.0
  Using cached protobuf-3.20.0-cp310-cp310-win_amd64.whl (903 kB)
Requirement already satisfied: sentencepiece in f:\automatic1111\venv\lib\site-packages (from open-clip-torch->clip-interrogator==0.6.0) (0.1.97)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\automatic1111\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in f:\automatic1111\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\automatic1111\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in f:\automatic1111\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (2022.12.7)
Requirement already satisfied: wcwidth>=0.2.5 in f:\automatic1111\venv\lib\site-packages (from ftfy->open-clip-torch->clip-interrogator==0.6.0) (0.2.6)
Installing collected packages: protobuf, transformers, clip-interrogator
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
```

**Comment by caj001** [comment]
Hi. I'm still experiencing an error with this.  I've installed clip-interrogator v0.6.0 but still, no luck. 

```
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "F:\Automatic1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\Automatic1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Automatic1111\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 9, in <module>
    import clip_interrogator
  File "F:\Automatic1111\venv\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>
    from .clip_interrogator import Config, Interrogator, LabelTable, list_caption_models, list_clip_models, load_list
  File "F:\Automatic1111\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 12, in <module>
    from transformers import AutoProcessor, AutoModelForCausalLM, BlipForConditionalGeneration, Blip2ForConditionalGeneration
ImportError: cannot import name 'BlipForConditionalGeneration' from 'transformers' (F:\Automatic1111\venv\lib\site-packages\transformers\__init__.py)
```
