### ISSUE TITLE
Install BUG las version 22.03.2023

### ISSUE THREAD

**Issue by ffdown** [pharmapsychotic/clip-interrogator-ext#28]
File "E:\AI\SDP\extensions\clip-interrogator-ext\install.py", line 14, in <module>
    launch.run_pip(f"install clip-interrogator=={CI_VERSION}", "requirements for CLIP Interrogator")
  File "E:\AI\SDP\launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "E:\AI\SDP\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for CLIP Interrogator.
Command: "E:\AI\SDP\venv\Scripts\python.exe" -m pip install clip-interrogator==0.6.0 --prefer-binary
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting clip-interrogator==0.6.0
  Downloading clip_interrogator-0.6.0-py3-none-any.whl (787 kB)
     -------------------------------------- 787.8/787.8 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: tqdm in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (4.64.1)
Requirement already satisfied: torchvision in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (0.14.1+cu116)
Requirement already satisfied: safetensors in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (0.2.7)
Requirement already satisfied: requests in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (2.25.1)
Collecting transformers>=4.27.1
  Downloading transformers-4.27.2-py3-none-any.whl (6.8 MB)
     ---------------------------------------- 6.8/6.8 MB 9.6 MB/s eta 0:00:00
Requirement already satisfied: torch in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (1.13.1+cu116)
Requirement already satisfied: Pillow in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (9.4.0)
Requirement already satisfied: open-clip-torch in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (2.7.0)
Requirement already satisfied: accelerate in e:\ai\sdp\venv\lib\site-packages (from clip-interrogator==0.6.0) (0.12.0)
Requirement already satisfied: regex!=2019.12.17 in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (2022.10.31)
Requirement already satisfied: filelock in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (3.9.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (0.12.1)
Requirement already satisfied: packaging>=20.0 in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (23.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (0.11.1)
Requirement already satisfied: pyyaml>=5.1 in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (6.0)
Requirement already satisfied: numpy>=1.17 in e:\ai\sdp\venv\lib\site-packages (from transformers>=4.27.1->clip-interrogator==0.6.0) (1.23.3)
Requirement already satisfied: colorama in e:\ai\sdp\venv\lib\site-packages (from tqdm->clip-interrogator==0.6.0) (0.4.6)
Requirement already satisfied: psutil in e:\ai\sdp\venv\lib\site-packages (from accelerate->clip-interrogator==0.6.0) (5.9.4)
Requirement already satisfied: typing-extensions in e:\ai\sdp\venv\lib\site-packages (from torch->clip-interrogator==0.6.0) (4.4.0)
Collecting protobuf==3.20.0
  Downloading protobuf-3.20.0-cp310-cp310-win_amd64.whl (903 kB)
     ------------------------------------- 903.8/903.8 kB 11.5 MB/s eta 0:00:00
Requirement already satisfied: ftfy in e:\ai\sdp\venv\lib\site-packages (from open-clip-torch->clip-interrogator==0.6.0) (6.1.1)
Requirement already satisfied: sentencepiece in e:\ai\sdp\venv\lib\site-packages (from open-clip-torch->clip-interrogator==0.6.0) (0.1.97)
Requirement already satisfied: idna<3,>=2.5 in e:\ai\sdp\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\ai\sdp\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in e:\ai\sdp\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in e:\ai\sdp\venv\lib\site-packages (from requests->clip-interrogator==0.6.0) (2022.12.7)
Requirement already satisfied: wcwidth>=0.2.5 in e:\ai\sdp\venv\lib\site-packages (from ftfy->open-clip-torch->clip-interrogator==0.6.0) (0.2.6)
Installing collected packages: protobuf, transformers, clip-interrogator
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6

stderr: WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5]   : 'E:\\AI\\SDP\\venv\\Lib\\site-packages\\google\\~0otobuf\\internal\\_api_implementation.cp310-win_amd64.pyd'
Check the permissions.

WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -otobuf (e:\ai\sdp\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (e:\ai\sdp\venv\lib\site-packages)

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: E:\AI\SDP\venv\Scripts\python.exe -m pip install --upgrade pip

**Comment by ffdown** [comment]
remove all directory with "~"
give us at start:
```
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "E:\AI\SDP\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\SDP\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\SDP\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 10, in <module>
    from clip_interrogator import Config, Interrogator, list_caption_models, list_clip_models
ImportError: cannot import name 'list_caption_models' from 'clip_interrogator' (E:\AI\SDP\venv\lib\site-packages\clip_interrogator\__init__.py)
```

**Comment by AndrewEdgers** [comment]
Same here

**Comment by xbwtyz** [comment]
+1

**Comment by ffdown** [comment]
`Edit: It seems that manually updating the clip_interrogator and restarting the environment fixed the issue?`
no it's not. Update in extension that same.

`E:\AI\SDP\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "E:\AI\SDP\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\SDP\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\SDP\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 10, in <module>
    from clip_interrogator import Config, Interrogator, list_caption_models, list_clip_models
ImportError: cannot import name 'list_caption_models' from 'clip_interrogator' (E:\AI\SDP\venv\lib\site-packages\clip_interrogator\__init__.py)`

**Comment by xbwtyz** [comment]
Idk what to tell you. I tried multiple times for the extension to work, then I updated my clip_interrogator which was a 5.x version, restarted my venv, and the extension worked.

**Comment by mart-hill** [comment]
Is this extension using transformers? Or rather, protobuf module is using it, hence there might lie the issue, maybe either re-add transformers 4.27.2 (or .3, depending, which one is cached), or reboot the OS, so the cache gets refreshed? I hope I'm not mixing things up... 🙂 
Dreambooth extension in "dev2" branch changed "transformers" package version, again, hence my rant about that package.
![image](https://user-images.githubusercontent.com/55754730/227619660-87a7d591-605b-4b92-bf53-f6359e1ae421.png)

**Comment by xbwtyz** [comment]
And its back:

Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 9, in <module>
    import clip_interrogator
  File "D:\stable-diffusion-webui\venv\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>
    from .clip_interrogator import Config, Interrogator, LabelTable, list_caption_models, list_clip_models, load_list
  File "D:\stable-diffusion-webui\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 12, in <module>
    from transformers import AutoProcessor, AutoModelForCausalLM, BlipForConditionalGeneration, Blip2ForConditionalGeneration
ImportError: cannot import name 'Blip2ForConditionalGeneration' from 'transformers' (D:\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)

**Comment by pharmapsychotic** [comment]
@xbwtyz please try deleting the clip-interrogator-ext folder from your extensions folder to remove it. then install it again on the extensions tab.

**Comment by mart-hill** [comment]
Even after latest update (clip_interrogator 0.5.4) the extension still seems to have trouble with protobuf installing - still creates these ~ folders (~otobuf or smilarly named), for some reason, and the `ERROR: Could not install packages due to an OSError: [WinError 5]   : 'E:\\AI\\SDP\\venv\\Lib\\site-packages\\google\\~0otobuf\\internal\\_api_implementation.cp310-win_amd64.pyd'
Check the permissions.` still persists.
