### ISSUE TITLE
ImportError: cannot import name 'BlipForConditionalGeneration' from 'transformers'

### ISSUE THREAD

**Issue by Vigilence** [pharmapsychotic/clip-interrogator-ext#29]
It seems that the new update has some sort of conflict with the built in clip_interrogator from automatic1111.  It causes issues with the number of beams setting.  Anything other than 1 causes an error readout, putting number of beams to 1 fixes the issue.  Removing the extension allows me to change the number of beams to any number, with successful interrogations.

```
Restarting UI...
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion-webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 9, in <module>
    import clip_interrogator
  File "E:\stable-diffusion-webui\venv\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>
    from .clip_interrogator import Config, Interrogator, LabelTable, list_caption_models, list_clip_models, load_list
  File "E:\stable-diffusion-webui\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 12, in <module>
    from transformers import AutoProcessor, AutoModelForCausalLM, BlipForConditionalGeneration, Blip2ForConditionalGeneration
ImportError: cannot import name 'BlipForConditionalGeneration' from 'transformers' (E:\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)
```

This error occurs when no other extensions are installed or enabled.

**Comment by Vigilence** [comment]
This error is actually caused by [dreambooth extension](https://github.com/d8ahazard/sd_dreambooth_extension/issues/1110).
