### ISSUE TITLE
Error running install.py f ------------ Error loading script: clip_interrogator_ext.py

### ISSUE THREAD

**Issue by bryanray** [pharmapsychotic/clip-interrogator-ext#30]
python: 3.10.6  •  
torch: 1.13.1+cu117  •  
xformers: 0.0.16rc425  •  
gradio: 3.16.2  •  
commit: [a9fed7c3]

first time installed this ext

===============================================================================
Error running install.py for extension Z:\sd\webui\extensions\clip-interrogator-ext.
Command: "Z:\sd\system\python\python.exe" "Z:\sd\webui\extensions\clip-interrogator-ext\install.py"
Error code: 1
stdout: Installing requirements for CLIP Interrogator

stderr: Traceback (most recent call last):
  File "Z:\sd\webui\extensions\clip-interrogator-ext\install.py", line 14, in <module>
    launch.run_pip(f"install clip-interrogator=={CI_VERSION}", "requirements for CLIP Interrogator")
  File "Z:\sd\webui\launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "Z:\sd\webui\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for CLIP Interrogator.
Command: "Z:\sd\system\python\python.exe" -m pip install clip-interrogator==0.6.0 --prefer-binary
Error code: 1
stdout: Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple

stderr: ERROR: Could not find a version that satisfies the requirement clip-interrogator==0.6.0 (from versions: 0.1.3, 0.1.4, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4)
ERROR: No matching distribution found for clip-interrogator==0.6.0

===============================================================================

restart UI

===============================================================================

Restarting UI...
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "Z:\sd\webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "Z:\sd\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\sd\webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 9, in <module>
    import clip_interrogator
ModuleNotFoundError: No module named 'clip_interrogator'

-----------------------

thats all,

pleassse help

**Comment by bryanray** [comment]
i think it lacks the requiremtn in the site-package, but how do i get it

**Comment by pharmapsychotic** [comment]
Please try again now. The extension is back to using 0.5.4
