### ISSUE TITLE
Interrogator tab doesnt show up, Installation Failed

### ISSUE THREAD

**Issue by LiJT** [pharmapsychotic/clip-interrogator-ext#34]
Error loading script: clip_interrogator_ext.py
Traceback (most recent call last):
  File "E:\stable-diffusion\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 9, in <module>
    import clip_interrogator
  File "E:\stable-diffusion\venv\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>
    from .clip_interrogator import Config, Interrogator, LabelTable, list_caption_models, list_clip_models, load_list
  File "E:\stable-diffusion\venv\lib\site-packages\clip_interrogator\clip_interrogator.py", line 12, in <module>
    from transformers import AutoProcessor, AutoModelForCausalLM, BlipForConditionalGeneration, Blip2ForConditionalGeneration
ImportError: cannot import name 'BlipForConditionalGeneration' from 'transformers' (E:\stable-diffusion\venv\lib\site-packages\transformers\__init__.py)

This is the Error I get, After removing the extension and install it back again the problem persist, no solution so far.... Please help

**Comment by CypherQube** [comment]
@pharmapsychotic  This extension is broken since the Auto1111 update

**Comment by pharmapsychotic** [comment]
oof, thanks for heads up. updating my auto1111 now to see whats up

**Comment by pharmapsychotic** [comment]
hey guys please give it a try now.

**Comment by LiJT** [comment]
@pharmapsychotic Thank you so much!
