### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Qfaqir** [pharmapsychotic/clip-interrogator-ext#53]
The last weeks I have not been able to use Clip Interrogator at all. I only get the error message below.

I have reinstalled automatik 1111, i have deleted and reinstalled the venv, i have deleted and reinstalled the extension.
Nothing works. When i try to analyse or caption a image this comes up. Permission denied. 
And i cant even find that directory that's being denied in my computer.

Anyone know how to fix this? 

_Loading CLIP Interrogator 0.5.4...
Traceback (most recent call last):
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 82, in image_analysis
    load(clip_model_name)
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 61, in load
    blip_model=shared.interrogator.load_blip_model().float()
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\modules\interrogate.py", line 102, in load_blip_model
    blip_model = models.blip.blip_decoder(pretrained=files[0], image_size=blip_image_eval_size, vit='base', med_config=os.path.join(paths.paths["BLIP"], "configs", "med_config.json"))
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\repositories\BLIP\models\blip.py", line 173, in blip_decoder
    model = BLIP_Decoder(**kwargs)
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\repositories\BLIP\models\blip.py", line 96, in __init__
    self.tokenizer = init_tokenizer()
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\repositories\BLIP\models\blip.py", line 187, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1760, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1308, in hf_hub_download
    _cache_commit_hash_for_specific_revision(storage_folder, revision, commit_hash)
  File "C:\Q Dropbox\Kent Q\100 Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 941, in _cache_commit_hash_for_specific_revision
    ref_path.write_text(commit_hash)
  File "C:\Program Files\Python310\lib\pathlib.py", line 1152, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "C:\Program Files\Python310\lib\pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\kentl\\.cache\\huggingface\\hub\\models--bert-base-uncased\\refs\\main'_

**Comment by pharmapsychotic** [comment]
hmm try deleting the `C:\Users\kentl\.cache\huggingface\hub` folder. It should re-download anything missing that is needed then next time you run.

**Comment by Djanghost** [comment]
@pharmapsychotic same error without any path, just : PermissionError: [Errno 13] Permission denied

**Comment by Djanghost** [comment]
@pharmapsychotic same error without any path, just : PermissionError: [Errno 13] Permission denied

I deleted the cache folder, but still the same.
