### ISSUE TITLE
No Interrogator Tab

### ISSUE THREAD

**Issue by daniel1024b** [pharmapsychotic/clip-interrogator-ext#63]
Hello. Please assist with below. Error loading Extension = no Tab:

*** Error loading script: clip_interrogator_ext.py
    Traceback (most recent call last):
      File "E:\Games\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Games\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Games\sd.webui\webui\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 10, in <module>
        import clip_interrogator
    ModuleNotFoundError: No module named 'clip_interrogator'

**Comment by nykwil** [comment]
I'm also seeing this on runpod

**Comment by alicercedigital** [comment]
We cant see the interrogator tab also. We are running the runpod Ultimate Stable Diffusion
