### ISSUE TITLE
please,I encountered trouble during insttallation.

### ISSUE THREAD

**Issue by Vxhikd** [pharmapsychotic/clip-interrogator-ext#68]
Loading CLIP Interrogator 0.6.0...
Loading caption model blip-base...
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Salesforce/blip-image-captioning-base/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BF0850F4C0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ce38a239-cb86-442d-894c-2db0a36b7fb0)')' thrown while requesting HEAD https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Salesforce/blip-image-captioning-base/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BF0850F4C0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ce38a239-cb86-442d-894c-2db0a36b7fb0)')' thrown while requesting HEAD https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/config.json
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002BF0850F4C0>, 'Connection to huggingface.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Salesforce/blip-image-captioning-base/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BF0850F4C0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1597, in get_hf_file_metadata
    r = _request_wrapper(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 417, in _request_wrapper
    response = _request_wrapper(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 452, in _request_wrapper
    return http_backoff(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_http.py", line 274, in http_backoff
    raise err
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Salesforce/blip-image-captioning-base/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BF0850F4C0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ce38a239-cb86-442d-894c-2db0a36b7fb0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1347, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 131, in image_to_prompt
    load(clip_model_name)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\extensions\clip-interrogator-ext\scripts\clip_interrogator_ext.py", line 71, in load
    ci = Interrogator(config)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\clip_interrogator\clip_interrogator.py", line 70, in __init__
    self.load_caption_model()
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\clip_interrogator\clip_interrogator.py", line 84, in load_caption_model
    caption_model = BlipForConditionalGeneration.from_pretrained(model_path, torch_dtype=self.dtype)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2305, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "E:\stable-diffusion-webui\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Salesforce/blip-image-captioning-base is not the path to a directory containing a file named config.json.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by Vxhikd** [comment]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Salesforce/blip-image-captioning-base is not the path to a directory containing a file named config.json.

**Comment by ljdhhhhh** [comment]
same problem
